-- Insert sample categories
INSERT INTO categories (name, slug, description, image, is_active) VALUES
('Travel Gear', 'travel-gear', 'Essential gear for your adventures', '/images/categories/travel-gear.jpg', true),
('Outdoor Clothing', 'outdoor-clothing', 'High-performance apparel for outdoor activities', '/images/categories/outdoor-clothing.jpg', true),
('Hiking Equipment', 'hiking-equipment', 'Professional hiking and mountaineering gear', '/images/categories/hiking-equipment.jpg', true),
('Camping & Tents', 'camping-tents', 'Shelter and camping essentials', '/images/categories/camping-tents.jpg', true),
('Water Sports', 'water-sports', 'Equipment for aquatic adventures', '/images/categories/water-sports.jpg', true),
('Electronics & Tech', 'electronics-tech', 'Travel-friendly technology and gadgets', '/images/categories/electronics-tech.jpg', true);

-- Insert sample products
INSERT INTO products (name, slug, description, short_description, price, sale_price, sku, stock, images, category_id, brand, colors, sizes, materials, features, is_active, is_featured, rating) VALUES
-- Travel Gear Category (id: 1)
('Premium Travel Backpack 65L', 'premium-travel-backpack-65l', 'Professional-grade travel backpack with multiple compartments, rain cover, and ergonomic design. Perfect for extended adventures and hiking expeditions.', 'Professional 65L travel backpack with rain cover', 5999.00, 4799.00, 'TB-001', 25, ARRAY['/images/products/backpack-65l-1.jpg', '/images/products/backpack-65l-2.jpg', '/images/products/backpack-65l-3.jpg'], 1, 'Lakbay Pro', ARRAY['Black', 'Navy Blue', 'Forest Green'], ARRAY['65L'], ARRAY['Ripstop Nylon', 'YKK Zippers'], ARRAY['Rain Cover', 'Laptop Compartment', 'Hydration Compatible', 'Multiple Pockets'], true, true, 4.8),

('Lightweight Daypack 30L', 'lightweight-daypack-30l', 'Perfect for day hikes and city exploration. Features include hydration system compatibility, multiple pockets, and comfortable shoulder straps.', 'Comfortable 30L daypack for hiking and travel', 2999.00, NULL, 'DP-001', 40, ARRAY['/images/products/daypack-30l-1.jpg', '/images/products/daypack-30l-2.jpg'], 1, 'Lakbay Pro', ARRAY['Black', 'Royal Blue', 'Orange'], ARRAY['30L'], ARRAY['Polyester', 'Mesh'], ARRAY['Hydration Compatible', 'Reflective Strips', 'Breathable Back Panel'], true, true, 4.6),

('Travel Organizer Set', 'travel-organizer-set', 'Complete set of packing cubes and organizers to keep your luggage neat and organized. Includes 6 pieces in different sizes.', '6-piece travel organizer and packing cube set', 1499.00, 1199.00, 'TO-001', 60, ARRAY['/images/products/organizer-set-1.jpg', '/images/products/organizer-set-2.jpg'], 1, 'Lakbay Pro', ARRAY['Grey', 'Navy', 'Burgundy'], ARRAY['Standard'], ARRAY['Nylon', 'Mesh'], ARRAY['6 Pieces', 'See-through Mesh', 'Zipper Closure', 'Lightweight'], true, false, 4.4),

-- Outdoor Clothing Category (id: 2)  
('All-Weather Hiking Jacket', 'all-weather-hiking-jacket', 'Waterproof and breathable hiking jacket with sealed seams, adjustable hood, and multiple pockets. Perfect for Philippine mountain weather.', 'Waterproof breathable hiking jacket', 3999.00, NULL, 'HJ-001', 30, ARRAY['/images/products/hiking-jacket-1.jpg', '/images/products/hiking-jacket-2.jpg', '/images/products/hiking-jacket-3.jpg'], 2, 'Mountain Pro', ARRAY['Charcoal', 'Forest Green', 'Navy Blue'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Gore-Tex', 'Polyester'], ARRAY['Waterproof', 'Breathable', 'Sealed Seams', 'Adjustable Hood'], true, true, 4.7),

('Quick-Dry Hiking Pants', 'quick-dry-hiking-pants', 'Lightweight, quick-dry hiking pants with UPF 50+ sun protection. Features multiple pockets and articulated knees for comfort.', 'Lightweight quick-dry hiking pants with UPF 50+', 2499.00, 1999.00, 'HP-001', 45, ARRAY['/images/products/hiking-pants-1.jpg', '/images/products/hiking-pants-2.jpg'], 2, 'Mountain Pro', ARRAY['Khaki', 'Charcoal', 'Olive'], ARRAY['28', '30', '32', '34', '36', '38'], ARRAY['Nylon', 'Spandex'], ARRAY['Quick-Dry', 'UPF 50+', 'Multiple Pockets', 'Articulated Knees'], true, false, 4.5),

('Moisture-Wicking Base Layer Set', 'moisture-wicking-base-layer-set', 'Complete base layer set including long-sleeve shirt and pants. Made from merino wool blend for temperature regulation and odor resistance.', 'Merino wool blend base layer set', 3499.00, NULL, 'BL-001', 20, ARRAY['/images/products/base-layer-1.jpg', '/images/products/base-layer-2.jpg'], 2, 'Thermal Pro', ARRAY['Black', 'Navy', 'Grey'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Merino Wool', 'Polyester'], ARRAY['Temperature Regulation', 'Odor Resistant', 'Moisture-Wicking', 'Seamless Construction'], true, true, 4.9),

-- Hiking Equipment Category (id: 3)
('Carbon Fiber Trekking Poles', 'carbon-fiber-trekking-poles', 'Ultra-lightweight carbon fiber trekking poles with cork grips and tungsten carbide tips. Adjustable and collapsible for easy packing.', 'Lightweight carbon fiber trekking poles', 4999.00, 4299.00, 'TP-001', 35, ARRAY['/images/products/trekking-poles-1.jpg', '/images/products/trekking-poles-2.jpg'], 3, 'Alpine Gear', ARRAY['Black', 'Blue'], ARRAY['Adjustable 100-135cm'], ARRAY['Carbon Fiber', 'Cork', 'Tungsten Carbide'], ARRAY['Ultra Lightweight', 'Shock Absorption', 'Quick Lock System', 'Collapsible'], true, true, 4.8),

('Professional Climbing Rope 60m', 'professional-climbing-rope-60m', 'Dynamic climbing rope suitable for sport climbing and mountaineering. UIAA certified with excellent handling characteristics.', 'UIAA certified 60m dynamic climbing rope', 8999.00, NULL, 'CR-001', 15, ARRAY['/images/products/climbing-rope-1.jpg', '/images/products/climbing-rope-2.jpg'], 3, 'Alpine Gear', ARRAY['Blue', 'Red', 'Green'], ARRAY['9.5mm x 60m'], ARRAY['Nylon Core', 'Polyester Sheath'], ARRAY['UIAA Certified', 'Dynamic', 'Dry Treatment', 'Middle Mark'], true, false, 4.7),

-- Camping & Tents Category (id: 4)
('4-Season Mountain Tent', '4-season-mountain-tent', 'Professional 2-person 4-season tent designed for extreme weather conditions. Features geodesic design and vestibule for gear storage.', 'Professional 2-person 4-season mountain tent', 15999.00, 13999.00, 'MT-001', 10, ARRAY['/images/products/mountain-tent-1.jpg', '/images/products/mountain-tent-2.jpg', '/images/products/mountain-tent-3.jpg'], 4, 'Summit Shelter', ARRAY['Orange', 'Yellow'], ARRAY['2-Person'], ARRAY['Ripstop Nylon', 'Aluminum'], ARRAY['4-Season', 'Geodesic Design', 'Vestibule', 'Easy Setup'], true, true, 4.9),

('Ultralight Backpacking Tent', 'ultralight-backpacking-tent', 'Ultra-lightweight 1-person tent perfect for solo backpacking adventures. Weighs only 1.2kg while maintaining weather protection.', 'Ultralight 1-person backpacking tent - 1.2kg', 12999.00, NULL, 'UT-001', 18, ARRAY['/images/products/ultralight-tent-1.jpg', '/images/products/ultralight-tent-2.jpg'], 4, 'Summit Shelter', ARRAY['Green', 'Grey'], ARRAY['1-Person'], ARRAY['Silnylon', 'Carbon Fiber'], ARRAY['Ultralight 1.2kg', 'Waterproof', 'Compact Pack', 'Quick Setup'], true, true, 4.6),

('Sleeping Bag -10°C Rating', 'sleeping-bag-minus-10c', 'Down-filled sleeping bag rated for -10°C. Perfect for high-altitude camping and cold weather expeditions.', 'Down sleeping bag rated for -10°C', 7999.00, 6999.00, 'SB-001', 25, ARRAY['/images/products/sleeping-bag-1.jpg', '/images/products/sleeping-bag-2.jpg'], 4, 'Thermal Pro', ARRAY['Blue', 'Red'], ARRAY['Regular', 'Long'], ARRAY['Down Fill', 'Ripstop Nylon'], ARRAY['-10°C Rating', 'Down Fill', 'Compression Sack', 'Draft Collar'], true, false, 4.8);

